navbarPage("Iconicity patterns in Sign Languges",
           tabPanel("About",
                    "Here will be a long nice text."),
           tabPanel("Search by word",
                      column(2,
                             selectInput('word_search', 'select the word:', 
                                unique(read.csv("iconisity_SL.csv", sep = "\t", stringsAsFactors = FALSE)$word),
                                selectize=TRUE),
                             selectInput("act", "Action", c("yes", "no", "all"), selected = "all"),
                             selectInput("loc", "Localization", c("yes", "no", "all"), selected = "all"),
                             selectInput("person", "Personification", c("yes", "no", "all"), selected = "all"),
                             selectInput("part_wholes", "Parts/wholes", c("yes", "no", "all"), selected = "all")
                             ),
                      column(10,
                             leaflet::leafletOutput("word_map"),
                      column(6,
                             DT::dataTableOutput("word_table"))
                    )),
           tabPanel("Search by sematic field",
                    fluidRow(
                      column(2,
                           selectInput('field_search', 'select the semantic field:', 
                                       unique(read.csv("iconisity_SL.csv", sep = "\t", stringsAsFactors = FALSE)$semantic.field),
                                       selectize=TRUE),
                           selectInput("act_f", "Action", c("yes", "no", "all"), selected = "all"),
                           selectInput("loc_f", "Localization", c("yes", "no", "all"), selected = "all"),
                           selectInput("person_f", "Personification", c("yes", "no", "all"), selected = "all"),
                           selectInput("part_wholes_f", "Parts/wholes", c("yes", "no", "all"), selected = "all"),
                           selectInput("iconicity_pattern_f", "Iconicity pattern",
                                       choices = c("object", "handling", "tracing", "contour"))
                    ),
                      column(6,
                             leaflet::leafletOutput("field_map")),
                      column(4,
                             DT::dataTableOutput("field_table")))))