navbarPage("Iconicity patterns in Sign Languges",
           tabPanel("Welcome",
                    includeMarkdown("welcome.md")),
           tabPanel("Concepts on the map",
                      column(2,
                             selectInput('word_search', 'select the word:', 
                                unique(read.csv("iconisity_SL.csv", sep = "\t", stringsAsFactors = FALSE)$word),
                                selectize=TRUE),
                             selectInput("act", "Action", c("yes", "no", "all"), selected = "all"),
                             selectInput("loc", "Localization", c("yes", "no", "all"), selected = "all"),
                             selectInput("person", "Personification", c("yes", "no", "all"), selected = "all"),
                             selectInput("part_wholes", "Parts/wholes", c("yes", "no", "all"), selected = "all")
                             ),
                      column(10,
                             leaflet::leafletOutput("word_map"),
                      column(6,
                             DT::dataTableOutput("word_table"))
                    )),
           tabPanel("Semantic fields on the map",
                      column(2,
                           selectInput('field_search', 'select the semantic field:', 
                                       unique(read.csv("iconisity_SL.csv", sep = "\t", stringsAsFactors = FALSE)$semantic.field),
                                       selectize=TRUE),
                           selectInput("act_f", "Action", c("yes", "no", "all"), selected = "all"),
                           selectInput("loc_f", "Localization", c("yes", "no", "all"), selected = "all"),
                           selectInput("person_f", "Personification", c("yes", "no", "all"), selected = "all"),
                           selectInput("part_wholes_f", "Parts/wholes", c("yes", "no", "all"), selected = "all"),
                           selectInput("iconicity_pattern_f", "Iconicity pattern",
                                       choices = c("object", "handling", "tracing", "contour"))),
                      column(6,
                             leaflet::leafletOutput("field_map")),
                      column(4,
                             DT::dataTableOutput("field_table"))),
           tabPanel("Graphs",
                    column(2,
                           selectInput('graph_field', 'select the semantic field:', 
                                       c("all", unique(read.csv("iconisity_SL.csv", sep = "\t", stringsAsFactors = FALSE)$semantic.field)),
                                       selectize=TRUE),
                           selectInput('graph_type', 'select the type of graph:', 
                                       c("absolute values", "percentage"),
                                       selectize=TRUE)),
                    column(6,
                           plotOutput("graph_picture")),
                    column(4,
                           DT::dataTableOutput("graph_table"))),
           tabPanel("Raw data",
                    fluidRow(column(1,""),
                             tagList("Download the data: ", a(".tsv", href="https://goo.gl/7j7jJV"))),
                    fluidRow(column(11,
                             DT::dataTableOutput("full_table")))),
           tabPanel("About",
                    includeMarkdown("about.md")))